apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: mysql
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: {{ .Values.database.serviceName }}
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: catalogdb