apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog

  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-app

spec:

{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: catalog
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: retail-store-app

  template:

    metadata:

      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"

{{- if .Values.opentelemetry.enabled }}
        instrumentation.opentelemetry.io/inject-sdk: "{{ .Values.opentelemetry.instrumentation }}"
{{- end }}

      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: catalog
        app.kubernetes.io/component: service
        app.kubernetes.io/owner: retail-store-app

    spec:

      serviceAccountName: {{ .Values.serviceAccount.name }}

      terminationGracePeriodSeconds: 30

      securityContext:
        fsGroup: 1000

{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

      containers:

        - name: catalog

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: catalog

            - secretRef:
                name: catalog-db

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000

            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL

            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          startupProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}

            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:

            - mountPath: /tmp
              name: tmp-volume

            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true

      volumes:

        - name: tmp-volume
          emptyDir:
            medium: Memory

        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: "{{ .Values.secrets.secretProviderClass }}"