replicaCount: 3

image:
  repository: tcollins520/retail-store-orders
  pullPolicy: IfNotPresent
  tag: "1.3.0"

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  name: orders
  targetPort: 8080

serviceAccount:
  name: orders

probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    periodSeconds: 5

  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10

resources:
  requests:
    cpu: 256m
    memory: 1Gi

  limits:
    cpu: 512m
    memory: 1.5Gi

# ---------------------------------------------------------
# PostgreSQL RDS Database Endpoint
# ---------------------------------------------------------
database:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: orders-postgres-db.cml0yuu2ka2y.us-east-1.rds.amazonaws.com:5432
  RETAIL_ORDERS_PERSISTENCE_NAME: ordersdb
  RETAIL_ORDERS_MESSAGING_PROVIDER: sqs
  RETAIL_ORDERS_MESSAGING_SQS_TOPIC: retail-dev-orders-queue
  #RETAIL_ORDERS_MESSAGING_SQS_TOPIC: https://sqs.us-east-1.amazonaws.com/180789647333/retail-dev-orders-queue

secrets:
  awsRegion: us-east-1
  secretName: retailstore-db-secret-1
  secretProviderClass: orders-db-secrets

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  karpenter.sh/capacity-type: on-demand

affinity: {}

tolerations: []

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: service
        app.kubernetes.io/instance: orders

  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: service
        app.kubernetes.io/instance: orders

podDisruptionBudget:
  enabled: true
  minAvailable: 2

opentelemetry:
  enabled: true
  instrumentation: default-instrumentation
  